## Упражнения по библиотеке Numpy

In [2]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [4]:
arr = np.random.randint(-10, 10, size=10)
arr[3:9] *= -1

**2.** Заменить максимальный элемент случайного массива на 0

In [9]:
max_elem = np.amax(arr)
max_indexes = np.where(arr == max_elem) # индексы максимальных элементов в случае повторения

arr[max_indexes]=0

**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [7]:
# matrix = np.array([[2,3],[4, 2], [3, 4]])
# [[2. 4. 3.]
#  [2. 4. 4.]
#  [3. 4. 3.]
#  [3. 4. 4.]
#  [2. 2. 3.]
#  [2. 2. 4.]
#  [3. 2. 3.]
#  [3. 2. 4.]]

rows = int(input("Input rows: ")) # 3
cols = int(input("Input cols: ")) # 2

matrix = np.zeros((rows, cols))

for i in range(rows):
    row_values = input(f"Input {cols} numbers (integer) through a space for a row {i}: ")
    elements = row_values.split()
    for j in range(cols):
        matrix[i][j] = elements[j]

arr_meshgrid = np.meshgrid(*matrix) # сетка для умножения
arr_product = np.vstack([arr_meshgrid[i].ravel() for i in range(arr_meshgrid.__len__())]).T
print('\n', arr_product)


Input rows: 3
Input cols: 2
Input 2 numbers (integer) through a space for a row 0: 1 2
Input 2 numbers (integer) through a space for a row 1: 2 3
Input 2 numbers (integer) through a space for a row 2: 4 5

 [[1. 2. 4.]
 [1. 2. 5.]
 [2. 2. 4.]
 [2. 2. 5.]
 [1. 3. 4.]
 [1. 3. 5.]
 [2. 3. 4.]
 [2. 3. 5.]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [8]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [2, 3, 4],
              [5, 6, 7], [8, 9, 1], [3, 4, 5], [6, 7, 8]])

B = np.array([[2, 3], [7, 8]])

rows = []
for i in range(len(A)):
    for j in range(len(B)):
        if np.isin(B[j], A[i]).all():
            rows.append(i)
            
print(rows) # [0,0,1]

[0, 2, 3, 7]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [10]:
matrix = np.array([[2, 2, 3], # строка из неравных знаечений
                   [3, 3, 3], 
                   [4, 5, 6], # строка из неравных знаечений
                   [7, 7, 8], # строка из неравных знаечений
                   [9, 9, 9], 
                   [1, 2, 3], # строка из неравных знаечений
                   [4, 4, 4],
                   [5, 5, 6], # строка из неравных знаечений
                   [7, 8, 9], # строка из неравных знаечений
                   [1, 1, 1]]) 

new_matrix = np.array([row for row in matrix if len(np.unique(row)) > 1])

print(new_matrix)

[[2 2 3]
 [4 5 6]
 [7 7 8]
 [1 2 3]
 [5 5 6]
 [7 8 9]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [14]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 9], [4, 5, 6]])

_, indexes = np.unique(matrix, axis=0, return_index=True)
matrix = matrix[np.sort(indexes)]

print(matrix)

[[1 2 3]
 [4 5 6]
 [4 5 9]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [39]:
from functools import reduce

# --------------------------------------------------------------------------------------------------
lst = [[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]
n = min(len(lst), len(lst[0]))

diagonal_elements = [lst[i][i] for i in range(n) if lst[i][i] is not None and lst[i][i] != 0]
mult_list = None if not diagonal_elements else reduce(lambda x, y: x*y, diagonal_elements)

# --------------------------------------------------------------------------------------------------
array = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])

diagonal_elements = np.diagonal(array)
mult_array = np.prod(diagonal_elements[diagonal_elements != 0])
# --------------------------------------------------------------------------------------------------
print(f'Результаты подсчета произведения: для list {mult_list} и для array {mult_array}') 


Результаты подсчета произведения: для list 3 и для array 3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [23]:
x_list = [1, 2, 2, 4]
y_list = [4, 2, 1, 2]

result_list = True if sorted(x_list) == sorted(y_list) else False

# --------------------------------------------------------------------------------------------------

x_array = np.array([1, 2, 2, 4])
y_array = np.array([4, 2, 1, 2])

result_array = np.array_equal(np.sort(x_array), np.sort(y_array))

# --------------------------------------------------------------------------------------------------

print(result_list, result_array)

True True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [38]:
lst = [6, 2, 0, 3, 0, 0, 5, 7, 0]

numbers_after_zero = [num for i, num in enumerate(lst[1:]) if lst[i] == 0]
max_list = max(numbers_after_zero) if numbers_after_zero else None

print(max_list)  # 5

# --------------------------------------------------------------------------------------------------
array = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

mask = np.hstack(([False], array[:-1] == 0))
max_array = np.max(array[mask])


print(max_array)  # 5

5
5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [48]:
def run_length_encoding_lst(x: list) -> tuple:
    if not x:
        return [], []

    values = [x[0]]
    counts = [1]

    for i in range(1, len(x)):
        if x[i] == x[i-1]:
            counts[-1] += 1
        else:
            values.append(x[i])
            counts.append(1)

    return values, counts

def run_length_encoding_np(x: np.array) -> tuple:
    starts = np.concatenate(([True], x[:-1] != x[1:], [True])) # 1 и последний(добавочный) элементы истины
    lengths = np.diff(np.where(starts)[0])
    values = x[starts[:-1]] # берем без последнего вымышленного
    return values, lengths

lst = [2, 2, 2, 3, 3, 3, 5]
array = np.array([2, 2, 2, 3, 3, 3, 5])

result_lst = run_length_encoding_lst(lst)
result_np = run_length_encoding_np(array)

print(result_lst, '\n', result_np)

([2, 3, 5], [3, 3, 1]) 
 (array([2, 3, 5]), array([3, 3, 1]))


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [12]:
import time
import random
import math
from scipy.spatial.distance import cdist

def euclidean_distances_np(X, Y):
    dists = np.sqrt(np.sum(X ** 2, axis=1)[:, np.newaxis] + np.sum(Y ** 2, axis=1) - 2 * np.dot(X, Y.T))
    return dists

def euclidean_distances_py(X,Y):
    distances = []
    for i, x in enumerate(X):
        row = []
        for j, y in enumerate(Y):
            dist = math.sqrt(sum([(a - b)**2 for a, b in zip(x, y)]))
            row.append(dist)
        distances.append(row)

X = np.random.rand(3, 2)
Y = np.random.rand(4, 2)
X_ls = [[random.random() for j in range(2)] for i in range(3)]
Y_ls = [[random.random() for j in range(2)] for i in range(4)]

start = time.time()
dists1 = euclidean_distances_np(X, Y)
end = time.time()
print(f"Numpy euclidean_distances: {end - start:.4f} seconds")

start = time.time()
dists2 = euclidean_distances_py(X_ls, Y_ls)
end = time.time()
print(f"Py euclidean_distances: {end - start:.4f} seconds")

start = time.time()
dists3 = cdist(X, Y, 'euclidean')
end = time.time()
print(f"Cdist: {end - start:.4f} seconds")

# assert np.allclose(dists1, dists3)
# assert np.allclose(dists2, dists3)

Numpy euclidean_distances: 0.0010 seconds
Py euclidean_distances: 0.0001 seconds
Cdist: 0.0001 seconds


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [13]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [15]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [18]:
average_calories = np.mean(calorie_stats)
average_calories

106.88311688311688

3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [19]:
calorie_stats_sorted = np.sort(calorie_stats)
calorie_stats_sorted

array([ 50.,  50.,  50.,  70.,  70.,  80.,  90.,  90.,  90.,  90.,  90.,
        90.,  90., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 120., 120., 120., 120., 120., 120., 120.,
       120., 120., 120., 130., 130., 140., 140., 140., 150., 150., 160.])

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [21]:
median_calories = np.median(calorie_stats)
median_calories

110.0

5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [22]:
nth_percentile = 1
while np.percentile(calorie_stats, nth_percentile) <= 60:
    nth_percentile += 1
    
nth_percentile

4

6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [24]:
more_calories = (calorie_stats >= 60).mean() * 100
more_calories

96.1038961038961

7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [26]:
calorie_std = np.std(calorie_stats)
calorie_std

19.35718533390827

8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [34]:
# Сравнение медианы и среднего значения поможет определить, 
# какое из них лучше отражает центральную тенденцию данных.
comparison = median_calories > average_calories if True else False

print(f"Среднее значение калорий в наборе данных конкурентов Mycrunch равно {average_calories}, \
      а медиана — {median_calories}. Это говорит о том, что большинство значений находятся около \
      или выше среднего, что подтверждается гистограммой распределения калорий. Таким образом, \
      среднее значение не является наиболее информативным показателем для описания данных, а медиана \
      отражает центральную тенденцию набора данных более точно")

print("В контексте маркетинга CrunchieMunchies, эти данные могут быть использованы для подчеркивания \
    относительно низкой калорийности CrunchieMunchies по сравнению с конкурентами. Однако, для более \
    точного сравнения, следует также учитывать другие параметры (цена, вкусовые характеристики и т.д.)")

Среднее значение калорий в наборе данных конкурентов Mycrunch равно 106.88311688311688,       а медиана — 110.0. Это говорит о том, что большинство значений находятся около       или выше среднего, что подтверждается гистограммой распределения калорий. Таким образом,       среднее значение не является наиболее информативным показателем для описания данных, а медиана       отражает центральную тенденцию набора данных более точно
В контексте маркетинга CrunchieMunchies, эти данные могут быть использованы для подчеркивания     относительно низкой калорийности CrunchieMunchies по сравнению с конкурентами. Однако, для более     точного сравнения, следует также учитывать другие параметры (цена, вкусовые характеристики и т.д.)
